/**
 * A deliberately small XML reader, just big enough for bank statement files.
 *
 * Not DOMParser: that exists in Obsidian's renderer but not under the test runner, and pulling in a
 * DOM shim to parse a file whose shape is this regular would be a lot of dependency for very little.
 * Not a general XML implementation either — no namespaces resolution, no DTDs, no entity definitions.
 * CAMT.053 is machine-generated by banks and stays firmly inside what this handles.
 */

export interface XmlNode {
	/** Tag name with any namespace prefix stripped, so `<ns:Ntry>` and `<Ntry>` read the same. */
	name: string;
	attrs: Record<string, string>;
	children: XmlNode[];
	/** Direct text content of this element, trimmed. Empty for elements that only contain children. */
	text: string;
}

const ENTITIES: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'" };

function decodeEntities(text: string): string {
	return text.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g, (match, body: string) => {
		if (body.startsWith("#x") || body.startsWith("#X")) {
			const code = parseInt(body.slice(2), 16);
			return isNaN(code) ? match : String.fromCodePoint(code);
		}
		if (body.startsWith("#")) {
			const code = parseInt(body.slice(1), 10);
			return isNaN(code) ? match : String.fromCodePoint(code);
		}
		return ENTITIES[body] ?? match;
	});
}

function stripPrefix(name: string): string {
	const colon = name.indexOf(":");
	return colon === -1 ? name : name.slice(colon + 1);
}

function parseAttrs(raw: string): Record<string, string> {
	const attrs: Record<string, string> = {};
	const re = /([\w:.-]+)\s*=\s*("([^"]*)"|'([^']*)')/g;
	let m: RegExpExecArray | null;
	while ((m = re.exec(raw))) {
		attrs[stripPrefix(m[1])] = decodeEntities(m[3] ?? m[4] ?? "");
	}
	return attrs;
}

/**
 * Parses `text` into a tree and returns the root element. Throws when there is no element at all;
 * tolerates trailing junk, unclosed trailing tags, and the usual prolog/comment/CDATA noise, because
 * a statement file that's 99% readable is worth reading.
 */
export function parseXml(text: string): XmlNode {
	const root: XmlNode = { name: "#document", attrs: {}, children: [], text: "" };
	const stack: XmlNode[] = [root];

	// Strip the pieces that carry no data before walking tags, so the walk stays a simple scan.
	const cleaned = text
		.replace(/<\?[\s\S]*?\?>/g, "")
		.replace(/<!--[\s\S]*?-->/g, "")
		.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, (_, inner: string) => inner)
		.replace(/<!DOCTYPE[^>]*>/gi, "");

	const tagRe = /<\s*(\/?)\s*([\w:.-]+)([^>]*?)(\/?)\s*>/g;
	let lastIndex = 0;
	let m: RegExpExecArray | null;

	while ((m = tagRe.exec(cleaned))) {
		const [full, closing, rawName, rawAttrs, selfClosing] = m;
		const between = cleaned.slice(lastIndex, m.index);
		if (between.trim()) {
			const current = stack[stack.length - 1];
			current.text = (current.text ? `${current.text} ` : "") + decodeEntities(between.trim());
		}
		lastIndex = m.index + full.length;

		const name = stripPrefix(rawName);
		if (closing) {
			// Pop to the matching element rather than assuming the file is perfectly balanced.
			for (let i = stack.length - 1; i > 0; i--) {
				if (stack[i].name === name) {
					stack.length = i;
					break;
				}
			}
			continue;
		}

		const node: XmlNode = { name, attrs: parseAttrs(rawAttrs), children: [], text: "" };
		stack[stack.length - 1].children.push(node);
		if (!selfClosing) stack.push(node);
	}

	const first = root.children[0];
	if (!first) throw new Error("No XML elements found in this file.");
	return first;
}

/** Every descendant (at any depth) with this tag name, in document order. */
export function findAll(node: XmlNode, name: string): XmlNode[] {
	const out: XmlNode[] = [];
	const walk = (n: XmlNode): void => {
		for (const child of n.children) {
			if (child.name === name) out.push(child);
			walk(child);
		}
	};
	walk(node);
	return out;
}

/** The first descendant with this tag name, searching depth-first. */
export function find(node: XmlNode, name: string): XmlNode | undefined {
	for (const child of node.children) {
		if (child.name === name) return child;
		const nested = find(child, name);
		if (nested) return nested;
	}
	return undefined;
}

/**
 * Text of the first descendant matching a path of tag names, where each step may be at any depth
 * below the previous one — `textAt(entry, "Amt")` and `textAt(entry, "RltdPties", "Cdtr", "Nm")`
 * both read naturally against CAMT's deep nesting without spelling out every intermediate element.
 */
export function textAt(node: XmlNode, ...path: string[]): string {
	let current: XmlNode | undefined = node;
	for (const step of path) {
		if (!current) return "";
		current = find(current, step);
	}
	return current?.text ?? "";
}
